export default {
    LOGIN: "LOGIN",
    SIGNUP: 'SIGNUP',
    IS_LOGIN: 'IS_LOGIN',
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    GET_BOOKS: "GET_BOOKS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    GET_CART: "GET_CART",
    SET_TOTAL: "SET_TOTAL"
}