export default {
    LOGIN: "LOGIN",
    SIGNUP: 'SIGNUP',
    IS_LOGIN: 'IS_LOGIN',
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    GET_BOOKS: "GET_BOOKS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    GET_CART: "GET_CART",
    SET_TOTAL: "SET_TOTAL",
    GET_PRODUCT_NAMES: "GET_PRODUCT_NAMES",
    SET_BOOK_DATA: 'SET_BOOK_DATA',
    SET_COLLEGE_DATA: 'SET_COLLEGE_DATA',
    GET_DOWNLOADS: 'GET_DOWNLOADS',
    SET_TO_DOWNLOADS: 'SET_TO_DOWNLOADS'
}